name: Go

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.20

      - name: Get dependencies
        run: go get -v -t -d ./...
        if: steps.go.outputs.GOOS == 'linux'

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

      - name: Install golangci-lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.39.0

      - name: Run golangci-lint
        run: golangci-lint run