name: Go

on: [push]
permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Get dependencies
        run: go get -v -t -d ./...
        if: steps.go.outputs.GOOS == 'linux'
      - name: Build
        run: go build -v ./cmd/server
      - name: Test
        run: go test -v ./...